// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhoLAmgiKVT80wCOfp1t1LT0FB-ate3A',
    appId: '1:712148613943:web:e9dbc2f38d9ac3d0a438b2',
    messagingSenderId: '712148613943',
    projectId: 'parcial4-b2211',
    authDomain: 'parcial4-b2211.firebaseapp.com',
    storageBucket: 'parcial4-b2211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3gkIYpyEN569DDwCSPV0U5N48GjCizY',
    appId: '1:712148613943:android:4601e3d42e99c6d3a438b2',
    messagingSenderId: '712148613943',
    projectId: 'parcial4-b2211',
    storageBucket: 'parcial4-b2211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1ET9RwUBN5W9w-qL_mqLaCG19S5PP0E',
    appId: '1:712148613943:ios:0e723591731b9b31a438b2',
    messagingSenderId: '712148613943',
    projectId: 'parcial4-b2211',
    storageBucket: 'parcial4-b2211.appspot.com',
    iosClientId: '712148613943-gh532nbothp760fn8ee86881qqvsife6.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial42565882012',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE1ET9RwUBN5W9w-qL_mqLaCG19S5PP0E',
    appId: '1:712148613943:ios:196887cff91266b3a438b2',
    messagingSenderId: '712148613943',
    projectId: 'parcial4-b2211',
    storageBucket: 'parcial4-b2211.appspot.com',
    iosClientId: '712148613943-9f7vl4234i0qhc70opbpd6tasop38t5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial42565882012.RunnerTests',
  );
}
